pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
      stage('Deliver') {
    steps {
        script {
            try {
                sh './jenkins/scripts/deliver.sh > output.log 2>&1'
            } catch (Exception ex) {
                currentBuild.result = 'FAILURE'
                echo "Error: ${ex.message}"
            }
        }
    }
}

    }
}
